### PR TITLE
Combined signal noise plot

### PR DESCRIPTION
**Pull request by crleblanc**
When plotting rf.signal or rf.noise we now plot both.  Resolves GeoNet/mtr#168.

Applying the proper scale factor to the threshold values.  Also added Y axis labels and labelling of threshold values which resolves GeoNet/mtr#194.

Added a left margin to the interactive plots to allow easier scrolling on mobile.

### CODE REVIEW

**Comment by sorennh** [comment]
Got the code installed, will do some testing now.

**Comment by crleblanc** [comment]
I just realised the final return in getDataYLabel and getFieldYLabel should return an error instead of nil (no error).

This should be a trivial fix, I'll do it next week. Probably on Tuesday after first aid training.

**Comment by crleblanc** [comment]
Ok Soren, should be all ready now.  It's also been rebased to master since master has had other changes merged.

**Comment by sorennh** [comment]
Moved to Combined signal noise plot #236 with re-based version.

**Pull request closed without merging**
