### PR TITLE
Proposed fix for GeoNet/mtr#225, change the typeID URL param to modelID

### PR DESCRIPTION
**Pull request by crleblanc**
See GeoNet/mtr#225 for more information on the problem.

### CODE REVIEW

**Comment by bpeng** [comment]
This caused another problem:

Clicking on the 'field' tab (/field/metrics) -> metrics (eg: for 'centre') -> returns empty list (No metrics available.) 
URL:
http://localhost:8081/field/metrics?modelID=centre
should it be:
http://localhost:8081/field/metrics?typeID=centre ?

**Comment by crleblanc** [comment]
Ok, looks like it'll need a bit more work.  I'll have a look next week.

**Comment by crleblanc** [comment]
@junghao do you mind having a look at this?  I was hoping it was just a typo, but that fixes one problem and causes another.  I'm not clear to me how we would decide when the URL should have typeID= and when it should be modelID= as the parameter.

**Comment by junghao** [comment]
The key for mtr-ui page parameters is : "to append what we lack (or we already got, sometimes)" rather than figure out an universal way.

I recommend to change getFieldMetricsPanel like this:

```
diff --git a/mtr-ui/field_page.go b/mtr-ui/field_page.go
index 799ddef..f248963 100644
--- a/mtr-ui/field_page.go
+++ b/mtr-ui/field_page.go
@@ -244,11 +244,17 @@ func (p *mtrUiPage) getFieldMetricsPanel() (err error) {

 	// Update header part of panel
 	for _, r := range p.Panels {
-		l := p.appendPageParam("/field/devices?modelID=" + r.ID)
-		m := idCount{Count: len(r.devices), ID: "Devices", Link: l}
+		var dl, ml string
+		if p.TypeID != "" {
+			dl = p.appendPageParam("/field/devices?modelID=" + r.ID)
+			ml = p.appendPageParam("/field/metrics?modelID=" + r.ID)
+		} else {
+			dl = p.appendPageParam("/field/devices?typeID=" + r.ID)
+			ml = p.appendPageParam("/field/metrics?typeID=" + r.ID)
+		}
+		m := idCount{Count: len(r.devices), ID: "Devices", Link: dl}
 		r.Values["devices"] = m
-		l = p.appendPageParam("/field/metrics?modelID=" + r.ID)
-		m = idCount{Count: r.Values["total"].Count, ID: "Metrics", Link: l}
+		m = idCount{Count: r.Values["total"].Count, ID: "Metrics", Link: ml}
 		r.Values["metrics"] = m
 	}
 	sort.Sort(panels(p.Panels))
```

I think it works.

**Comment by crleblanc** [comment]
Thanks @junghao.  I've rebased, applied your fix and pushed to this branch.

**Pull request merged**
