### PR TITLE
Added /field/metric CSV function and resolution option to all CSV functions

### PR DESCRIPTION
**Pull request by crleblanc**
Also added the resolution option for csv methods, so we can limit
the size of the data used in the interactive plots.

This PR for mtr-api should let me submit a PR for the interactive plots.  It's getting to be a long lived branch with lots of changes so I'd like to get it merged before too long.  This change to mtr-api is relatively small so should be quick.

### CODE REVIEW

**Comment by gclitheroe** [comment]
Hi,

I might have missed something.  I'm guessing that you want the plots in NZT?
I don't think using time.Local() is going to do what you want when the service is running in AWS Sydney?

api services should return UTC by default (not some local time zone).

It would be very useful to be able to make the plots in UTC or NZT (NZST or NZDT) so maybe a query parameter to mtr-ui or mtr-api to set the TZ to return data in?

**Comment by crleblanc** [comment]
Opps, I forgot about the server possibly being in a different time zone.

The reason for using local time is that dygraph displays dates and times which look a little strange if they're in UTC.  I like your idea of UTC by default and having the JS code modify the offset.  Dygraphs have a "labelsUTC" option so I'll look into that.

I'll remove the local time conversion from this PR and add a comment when it's ready.

**Comment by crleblanc** [comment]
Ok, it's back to UTC times.  Should be ready to merge.

**Comment by crleblanc** [comment]
Now rebased to include weft.toml, along with modifications required by this branch.  Should be good to go.

**Pull request merged**
